Add coingecko id list file and update `getrate`
oceanprotocol/df-py pull request #325
Opened 2022-10-05 08:47 UTC by trizin

Fixes #324

Changes proposed in this PR:

- Add coingecko id list and update `getrate`

2022-10-05 11:52 UTC, trentmc requested changes

2022-10-05 11:52 UTC, trentmc commented on util/getrate.py
> +    with open(
Separate this into >1 lines and make each line do exactly one thing

2022-10-08 14:53 UTC, idiom-bytes approved these changes
Looks like you split per line as requested

2022-10-25 21:10 UTC, trentmc approved these changes
Approved. Sorry I missed this earlier. 

Please merge from main into this branch, before merging this branch to main.

2022-10-27 13:02 UTC, merged