Automate funding distribution
oceanprotocol/df-py pull request #389
Opened 2022-12-06 10:36 UTC by trizin

Fixes #388

Changes proposed in this PR:

- Run tests in the workflow before calculating rewards.
- Automate funding distribution.

2022-12-07 06:59 UTC, idiom-bytes commented
Is this good to go?

2022-12-20 14:57 UTC, alexcos20 commented
lgtm, but we may change some logic during today's sprint planning

2022-12-20 14:57 UTC, alexcos20 approved these changes

2022-12-20 17:12 UTC, alexcos20 requested changes

2022-12-20 17:12 UTC, alexcos20 commented on util/dispense.py
> +def dispense_passive(ocean, feedistributor, amount):
this is broken

2022-12-20 19:13 UTC, alexcos20 approved these changes

2022-12-21 09:38 UTC, merged