Add challenge DF into active rewards workflow
oceanprotocol/df-py pull request #657
Opened 2023-06-27 12:05 UTC by trizin

Fixes #656

Changes proposed in this PR:

- Add challenge DF into active rewards workflow

2023-06-29 14:30 UTC, calina-c requested changes

2023-06-29 14:58 UTC, calina-c requested changes

2023-06-29 14:58 UTC, calina-c commented on df_py/challenge/judge.py
> +        raise Exception(f"_get_txs: An error occured, {result}")
can you please add a test as well?

2023-07-03 05:39 UTC, calina-c approved these changes

2023-07-03 06:25 UTC, calina-c commented
@trizin I got this up to date and ready to merge (merged main, resolved all conversations etc.) but I will wait for you to merge it.

2023-07-20 18:25 UTC, idiom-bytes commented on df_py/util/dftool_module.py
> +    )
nice 1

2023-07-21 01:05 UTC, idiom-bytes commented on df_py/challenge/test/test_judge.py
> +                        "oldOwner": {"id": "0xfrom2"},
I haven't looked at the rest of judge-related logic, and this is extremely minor/not the changelist. but, is `oldOwner` supposed to be `originalOwner`?

2023-07-21 01:13 UTC, idiom-bytes approved these changes
Looks good, thanks for the tests!

2023-07-25 21:22 UTC, merged