Use OCEAN for challenge DF rewards
oceanprotocol/df-py pull request #660
Opened 2023-06-28 10:29 UTC by trizin

Fixes #658

Changes proposed in this PR:

- Use OCEAN for challenge DF rewards

2023-06-28 12:49 UTC, trentmc requested changes

2023-06-28 12:49 UTC, trentmc commented on df_py/challenge/calc_rewards.py
> +    rewards_in_ocean = get_challenge_reward_amounts_in_ocean(at_date)
Why do you even need the method "get_challenge_reward_amounts_in_usdt()"?

2023-06-28 12:49 UTC, trentmc commented on df_py/challenge/csvs.py
> +    f = "challenge_data.csv"
I'm surprised this is being changed here. It's outside the scope of this issue.

And if this change isn't breaking things outside of df-py (in df-sql), maybe it's a sign that we need to test more throughly.

2023-06-29 05:53 UTC, calina-c approved these changes
I thought we should send rewards in USDT but this is MUCH simpler if all right with everyone.

2023-07-02 00:02 UTC, trentmc approved these changes

2023-07-03 05:50 UTC, merged